### ISSUE TITLE
Add "Development Practice/Coding Style" section to handbook

### ISSUE THREAD

**Issue by kelynch** [pulibrary/rdss-handbook#118]
Include https://samvera.github.io/review.html 

Reference https://github.com/pulibrary/dls-handbook/blob/a4a993b59f6259843ad4792d895369c69b29a1bd/development_practice.md#L59 for potential pointers.

## Acceptance Criteria

- [ ] The rdss-handbook has a `development_practice.md`
- [ ] Copy or link to and review the DLS and samvera pages

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/rdss-handbook/118?planning-poker) with Zenhub @bess @jrgriffiniii @kelynch
