### ISSUE TITLE
Provide documentation for ThesisCentral SAML/Shibboleth X.509 Updates

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/rdss-handbook#242]
There are additional steps for providing X.509 updates to the ThesisCentral server infrastructure which require that RDSS request the direct support of IAM within the OIT (please see https://github.com/pulibrary/rdss-catchall/issues/120 and https://github.com/pulibrary/dspace-development/issues/716 for reference). This process should be documented in order to ensure that these steps are not overlooked in future updates for the X.509 certificates.

**Comment by kelynch** [comment]
We are moving to a hosted solution for ThesisCentral, so this ticket is no longer relevant, closing this.
