### ISSUE TITLE
Document monitoring for Globus infrastructure

### ISSUE THREAD

**Issue by kelynch** [pulibrary/rdss-handbook#99]
Document strategy and setup for monitoring Globus infrastructure, including:

- [x] Honeybadger for Globus endpoints
       https://app.honeybadger.io/projects/103564/sites
- [x] AWS monitoring S3 buckets for Globus storage
      Check with @kayiwa if this already exists, if not ticket it in the appropriate repo ( maybe? )
      There is a ticket for this(https://github.com/pulibrary/ops-catchall/issues/22)

Accptence criteria:

- [x] The documentation should be addition section in in https://github.com/pulibrary/rdss-handbook/blob/main/globus.md
- [x] Also add a monitoring.md in pdc-describe/docs and point to [Globus document in the handbook](https://github.com/pulibrary/rdss-handbook/blob/main/globus.md)
- [x] (optional) ticket for AWS monitoring in https://github.com/pulibrary/ops-catchall or better place from @kayiwa 
- [ ] (if above ticket for AWS monitoring is not needed) Add a section to pdc-describe/docs/monitoring for AWS.  May be as simple as linking to some documentation that exists.

**Comment by carolyncole** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/rdss-handbook/99?planning-poker) with Zenhub @mccalluc

**Comment by carolyncole** [comment]
Closing this ticket, pulibrary/ops-catchall#22 exists, and we do not have anything additional to document until that has been completed
